FROM cleverage/eav-manager:php7.2
LABEL maintainer="Jean-Yves CAMIER <jycamier@clever-age.com>"

ENV PHP_INI_SCAN_DIR :/home/docker/etc/php7

ENV INIT_XDEBUG_ACTIVATED 0
ENV INIT_XDEBUG_IDEKEY PHPSTORM
ENV INIT_XDEBUG_REMOTE_PORT 9000

COPY devfiles /

USER root
RUN apk --update add \
        php-xdebug@php \
        nano \
        zsh && \
    rm -rf /var/cache/apk/* && \
    rm -rf /etc/php7/conf.d/00_xdebug.ini && \
    wget --output-document=/usr/bin/psysh https://psysh.org/psysh && \
    chmod +x /usr/bin/psysh

USER docker
RUN sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" || true

COPY --chown=docker:docker devhome /

RUN HOST_IP="$(/sbin/ip route | /usr/bin/awk 'NR==1 {print $3}')" && \
    sed -i "s/xdebug\.remote_host\=.*/xdebug\.remote_host\=${HOST_IP}/g" /home/docker/etc/php7/00-xdebug.ini

EXPOSE 9000
